### ISSUE TITLE
【报错信息】AttributeError: 'HTTPResponse' object has no attribute 'strict'

### ISSUE THREAD

**Issue by kurisaW** [kurisaW/Summer-of-Open-Source#15]
问题描述：在激活esp-idf及esp-matter环境后，选择一个matter sample工程执行`idf.py set-target esp32c3`命令发生报错，参考以下issue，应该可以解决问题

* https://github.com/espressif/esp-idf/issues/11340
* https://github.com/espressif/idf-component-manager/issues/31#issuecomment-1535984388

**Comment by shenguoqing1** [comment]
windoes上这个问题怎么解决

**Comment by kurisaW** [comment]
你是指在windows下使用matter环境还是用的WSL2啊 @shengguoqing1
